---
- remote_user: root
  hosts: master
  tasks:
  - name: copy start_master.sh 
    copy: src=./start_master.sh dest=/tmp/start_master.sh
  - name: start installing master
    command: /bin/sh /tmp/start_master.sh --cluster-name={{ cluster_name }} --etcd-servers-ip={{ etcd_servers_ip }} --apiserver-count={{ apiserver_count }}
    register: result
    vars:
      - cluster_name: "{{ hostvars[inventory_hostname]['cluster_name'] }}"
      - apiserver_count: "{{ hostvars[inventory_hostname]['apiserver_count'] }}"
      - etcd_servers_ip: "{{ groups['etcd'] | join(',') }}"
  - debug:
      msg: "{{result.stdout}}"
  - debug:
      msg: "{{result.stderr}}"
  - name: clear start_master.sh
    command: rm -f /tmp/start_master.sh
